---
- name: Create VPC
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create VPC stack
      cloudformation:
        region: "{{ region }}"
        stack_name: "vpc-{{ vpc_env }}"
        state: present
        template: "../cf_templates/json/vpc.json"
        template_parameters:
          region: "{{ region }}"
          vpcCidr: "{{ vpc_cidr }}"
          vpcEnv: "{{ vpc_env }}"
          appSubnets: "{{ app_subnets }}"
          dataSubnets: "{{ data_subnets }}"
          serviceSubnets: "{{ service_subnets }}"
          sshKey: "{{ ssh_key }}"
