---
- name: Launch Jenkins Slave Host
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "../{{ env }}/group_vars/jenkins_slave"
  tasks:
    - name: Get hosted zone info
      cloudformation_stack_facts: stack_name=hostedzone region={{ region }}
      register: hostedzone
    - name: Get vpc info
      cloudformation_stack_facts: stack_name=vpc-{{ vpc_env }} region={{ region }}
      register: vpc
    - name: Get puppetmaster info
      cloudformation_stack_facts: stack_name=puppetmaster-{{ vpc_env }} region={{ region }}
      register: puppetmaster
    - name: Create Jenkins Slave stack
      cloudformation:
        region: "{{ region }}"
        stack_name: "jenkins-slave-{{ vpc_env }}"
        state: present
        template: "../cf_templates/json/jenkins_slave.json"
        template_parameters:
          vpcEnv: "{{ vpc_env }}"
          vpcId: "{{ vpc.stack_outputs.vpcId }}"
          ami: "{{ ami }}"
          instanceType: "{{ instance_type }}"
          sshKey: "{{ ssh_key }}"
          serviceSubnetAId: "{{ vpc.stack_outputs.serviceSubnetAId }}"
          puppetEnv: "{{ env }}"
          puppetRole: "{{ puppet_role }}"
          puppetmasterPrivateDnsName: "{{ puppetmaster.stack_outputs.puppetmasterPrivateDnsName }}"
          serviceSubnetCIDRs: "{{ service_subnets }}"
          hostedZoneId: "{{ hostedzone.stack_outputs.hostedZoneId }}"
          hostedZoneName: "{{ hostedzone.stack_outputs.hostedZoneName }}"
